const images = {
  //back: require('../Images/back.png'),
  splash: require('../Images/splash.png'),
  bg_img: require('../Images/bg_img.png'),
  fb_icon: require('../Images/fb_icon.png'),
  email: require('../Images/email.png'),
  back: require('../Images/back.png'),
  logo: require('../Images/logo.png'),
  plus: require('../Images/plus.png'),
  key: require('../Images/key.png'),
  profile_icon_placeholder: require('../Images/profile_icon_placeholder.png'),
  camera: require('../Images/camera.png'),
  gallery: require('../Images/gallery.png'),
  qr_code: require('../Images/qr_code.png'),
  cart: require('../Images/cart.png'),
  home: require('../Images/home.png'),
  hot: require('../Images/hot.png'),
  nearby: require('../Images/nearby.png'),
  notifications: require('../Images/notifications.png'),
  profile: require('../Images/profile.png'),
  search: require('../Images/search.png'),
  close: require('../Images/close.png'),
  direction: require('../Images/direction.png'),
  offer: require('../Images/offer.png'),
  offer_shadow: require('../Images/offer_shadow.png'),
  star_small: require('../Images/star_small.png'),
  star: require('../Images/star.png'),
  shadow_top: require('../Images/shadow_top.png'),
  shadow_bottom: require('../Images/shadow_bottom.png'),
  increase: require('../Images/increase.png'),
  decrease: require('../Images/decrease.png'),
  closeBtn: require('../Images/closeBtn.png'),
  radio_btn: require('../Images/radio_btn.png'),
  selected_radio_btn: require('../Images/selected_radio_btn.png'),
  plus_white: require('../Images/plus_white.png'),
  notification_logo: require('../Images/notification_logo.png'),
  edit_icon: require('../Images/edit_icon.png'),
  right_icon: require('../Images/right_icon.png'),
  edit: require('../Images/edit.png'),
  success: require('../Images/success.png'),
  img_placeholder: require('../Images/img_placeholder.png'),
  rect_img_placeholder: require('../Images/rect_img_placeholder.png'),
  small_image_placeholder: require('../Images/small_image_placeholder.png'),
};

export default images;
